defaults:
  - dataset: easy



model_id: nq
mode: eval
cuda:
per_gpu_train_batch_size: 4
per_gpu_train_batch_size_synth: 8
per_gpu_train_batch_size_tct: 8
per_gpu_train_batch_size_crl: 8
learning_rate: 2e-5
adam_epsilon: 1e-8
weight_decay: 0.0
num_train_epochs: 3
max_sequence_length: 4096
doc_stride: 2048
max_query_length: 36
logging_steps: 20
max_grad_norm: 1.0 
model_path: #/mnt/nas2/jungbin/research/TemporalQA/Time-Sensitive-QA/outputs/2023-03-30/05-27-48/checkpoint-epoch-1 #'/mnt/nas2/jungbin/research/TemporalQA/Time-Sensitive-QA/BigBird/checkpoints/ckp_nq_timeqa'
n_gpu:
freeze: False
CRL: False 
multi_task: False
k:
tct:
k_tct:
k_crl:
use_bert: False